"""Абстракция поведения аппаратной части обьекта тестирования"""

from typing import Protocol

from entities.data_objects.dut_hardware import NetworkInterface
from entities.data_objects.elementary import NetworkRole, StatusNI


class IHardwareManager(Protocol):
    """Абстракция управления аппаратной частью"""

    def get_interface_by_id(self, interface_id: str) -> NetworkInterface | None: ...
    def get_free_interfaces(self) -> list[NetworkInterface]: ...
    def get_interfaces_by_role(self, role: NetworkRole) -> list[NetworkInterface]: ...
    def set_interface_status(self, interface_id: str, status: StatusNI) -> bool: ...


class IHardwareMonitor(Protocol):
    """Абстракция мониторинга аппаратной части"""

    def get_system_metrics(self) -> dict: ...
    def get_temperature_readings(self) -> dict: ...
    def get_power_consumption(self) -> float: ...
    def validate_hardware_configuration(self) -> bool: ...


class IHardwareStatusManager(Protocol):
    """Абстракция управления статусами"""

    def mark_interface_as_busy(self, interface_id: str) -> bool: ...
    def mark_interface_as_free(self, interface_id: str) -> bool: ...
    def mark_interface_as_working(self, interface_id: str) -> bool: ...
    def get_interface_status(self, interface_id: str) -> StatusNI | None: ...
