"""Интерфейсы реализаций аппаратной части"""

from typing import Protocol

from back_pytrafficforge.entities.data_objects.dut_hardware import (
    DUTHardwareData,
    NetworkInterface,
)
from back_pytrafficforge.entities.data_objects.elementary import NetworkRole, StatusNI


class IDUTHardwareProvider(Protocol):
    """Интерфейс реализации DUT Hardware - объединяет данные и поведение"""

    @property
    def _data(self) -> DUTHardwareData: ...

    def get_interface_by_id(self, interface_id: str) -> NetworkInterface | None: ...
    def get_free_interfaces(self) -> list[NetworkInterface]: ...
    def get_interfaces_by_role(self, role: NetworkRole) -> list[NetworkInterface]: ...
    def set_interface_status(self, interface_id: str, status: StatusNI) -> bool: ...

    def get_system_metrics(self) -> dict: ...
    def get_temperature_readings(self) -> dict: ...
    def get_power_consumption(self) -> float: ...
    def validate_hardware(self) -> bool: ...

    def mark_interface_as_busy(self, interface_id: str) -> bool: ...
    def mark_interface_as_free(self, interface_id: str) -> bool: ...
    def mark_interface_as_working(self, interface_id: str) -> bool: ...
